Add MSSQL  Autoscaler, Ops Weebhook and New Version 2022-CU14
kubedb/installer pull request #1272
Opened 2024-09-05 06:27 UTC by Neaj-Morshad-101

Signed-off-by: Neaj Morshad <neaj@appscode.com>

2024-09-25 11:06 UTC, souravbiswassanto approved these changes

2024-09-26 07:57 UTC, ArnobKumarSaha requested changes

2024-09-26 07:57 UTC, ArnobKumarSaha commented on charts/kubedb-webhook-server/values.yaml
> +  MSSQLServer: true
Make it false

2024-09-26 14:49 UTC, ArnobKumarSaha approved these changes

2024-09-26 14:49 UTC, merged