Add Cassandra version jammy
kubedb/installer pull request #1287
Opened 2024-09-16 11:06 UTC by sabbir-hossain70

Fixes https://github.com/kubedb/internal/issues/1221

2024-09-20 13:27 UTC, tapojit047 submitted a review, later dismissed
LGTM!

2024-09-25 11:25 UTC, ArnobKumarSaha requested changes

2024-09-25 11:25 UTC, ArnobKumarSaha commented on charts/kubedb-webhook-server/values.yaml
> +  Cassandra: true
false

Run `make gen fmt` after the change

2024-09-25 12:51 UTC, ArnobKumarSaha approved these changes

2024-09-25 12:52 UTC, merged