Add MySQL Archiver Restic Physical Backup/Restore Support
kubedb/installer pull request #1439
Opened 2024-12-02 05:40 UTC by sheikh-arman

2024-12-13 05:19 UTC, ishtiaqhimel requested changes

2024-12-13 05:19 UTC, ishtiaqhimel commented on catalog/kubestash/raw/mysql/mysql-backup-function.yaml
> +---
Remove this.

2024-12-13 05:19 UTC, ishtiaqhimel commented on catalog/kubestash/raw/mysql/mysql-xtrabackup-function.yaml
> +---
Remove this.

2024-12-13 05:27 UTC, ishtiaqhimel requested changes
Change in the addon if needed

2024-12-13 05:27 UTC, ishtiaqhimel commented on catalog/kubestash/raw/mysql/mysql-xtrabackup-function.yaml
> +  - --data-directory=${datadir:=}
`--data-dir=${dataDir:=}`

2024-12-13 05:27 UTC, ishtiaqhimel commented on catalog/kubestash/raw/mysql/mysql-xtrabackup-restore-function.yaml
> +  - --data-directory=${datadir:=}
`--data-dir=${dataDir:=}`

2024-12-13 05:57 UTC, ishtiaqhimel submitted a review, later dismissed

2025-01-09 11:42 UTC, ArnobKumarSaha approved these changes

2025-01-09 11:42 UTC, merged