Add Support for Redis Version 7.0.4
kubedb/installer pull request #517
Opened 2022-07-29 08:56 UTC by Shaad7

Signed-off-by: Shaad7 <abdullah.alshaad@appscode.com>

2022-08-01 06:53 UTC, hossainemruz requested changes
Please update the task version and regenerate the chart.

2022-08-01 06:53 UTC, hossainemruz commented on catalog/raw/redis/redis-7.0.4.yaml
> +        name: redis-backup-6.2.5
Use `redis-backup-7.0.4`

2022-08-01 06:53 UTC, hossainemruz commented on catalog/raw/redis/redis-7.0.4.yaml
> +        name: redis-restore-6.2.5
Use `redis-restore-7.0.4`

2022-08-01 07:00 UTC, Shaad7 commented on catalog/raw/redis/redis-7.0.4.yaml
> +        name: redis-restore-6.2.5
Updated

2022-08-01 07:00 UTC, Shaad7 commented on catalog/raw/redis/redis-7.0.4.yaml
> +        name: redis-backup-6.2.5
Updated

2022-08-02 10:44 UTC, hossainemruz approved these changes

2022-08-02 10:48 UTC, merged