Add druid kubedb-metric template
kubedb/installer pull request #956
Opened 2024-03-22 12:53 UTC by tapojit047

2024-03-25 05:50 UTC, raihankhan requested changes

2024-03-25 05:50 UTC, raihankhan commented on charts/kubedb-metrics/templates/druid/kubedb-com-druid.yaml
> +      help: "Solr overseer node storage class information"
remove solr typos

2024-03-29 06:04 UTC, AshrafulHaqueToni commented on charts/kubedb-grafana-dashboards/dashboards/druid/druid-summary.json
> +          "expr": "(kubelet_volume_stats_used_bytes + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"^$app.*\",namespace=~\"$namespace\"}) ",
Replace `^$app.*` to `$app-brokers-\\\\d+$|$app-coordinators-\\\\d+$|$app-historicals-\\\\d+$|$app-middlemanagers-\\\\d+$|$app-routers-\\\\d+$|$app-overlords-\\\\d+$`

2024-04-24 09:18 UTC, ArnobKumarSaha approved these changes

2024-04-24 09:18 UTC, merged